# Generated by Django 4.2.7 on 2023-12-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nam',
        ),
    ]
