# Generated by Django 4.2.7 on 2023-12-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='car.carmodel'),
        ),
    ]
