# Generated by Django 4.2.7 on 2023-12-15 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0005_comment_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
