# Generated by Django 4.2.7 on 2023-12-15 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0007_remove_carmodel_user_carmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
